package com.banka1.stock_service.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * JPA entity representing an FX pair stored in the {@code forex_pair} table.
 *
 * <p>The persistent state stores the reference metadata for one quoted currency pair.
 * In this model, the stored {@code exchangeRate} acts as the current pair price used
 * for derived notional and maintenance-margin calculations.
 *
 * <p>The pair uses:
 *
 * <ul>
 *     <li>{@code ticker} as the stable business identifier, for example {@code EUR/USD}</li>
 *     <li>{@code baseCurrency} and {@code quoteCurrency} to describe the quoted pair</li>
 *     <li>{@code liquidity} to capture a coarse market-depth classification</li>
 * </ul>
 */
@Entity
@Table(name = "forex_pair")
@Getter
@Setter
public class ForexPair {

    /**
     * Standard contract size used for all FX pairs in this domain model.
     */
    public static final int CONTRACT_SIZE = 1_000;

    /**
     * Multiplier used to derive maintenance margin from the current nominal value.
     */
    private static final BigDecimal MAINTENANCE_MARGIN_RATE = new BigDecimal("0.10");

    /**
     * Technical primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique FX ticker used as the stable business key for imports.
     */
    @Column(name = "ticker", nullable = false, length = 32, unique = true)
    private String ticker;

    /**
     * ISO currency code of the pair base currency, for example {@code EUR}.
     */
    @Column(name = "base_currency", nullable = false, length = 3)
    private String baseCurrency;

    /**
     * ISO currency code of the pair quote currency, for example {@code USD}.
     */
    @Column(name = "quote_currency", nullable = false, length = 3)
    private String quoteCurrency;

    /**
     * Current quoted exchange rate used as the pair price in derived calculations.
     */
    @Column(name = "exchange_rate", nullable = false, precision = 19, scale = 8)
    private BigDecimal exchangeRate;

    /**
     * Liquidity bucket used to classify the pair for future trading logic.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "liquidity", nullable = false, length = 16)
    private Liquidity liquidity;

    /**
     * Returns the fixed contract size for this FX pair.
     *
     * @return contract size, always {@value #CONTRACT_SIZE}
     */
    public int getContractSize() {
        return CONTRACT_SIZE;
    }

    /**
     * Derives nominal value as {@code contractSize * exchangeRate}.
     *
     * <p>Example:
     * if {@code contractSize = 1000} and {@code exchangeRate = 1.08350},
     * the derived nominal value is {@code 1083.50000}.
     *
     * @return derived nominal value
     */
    public BigDecimal calculateNominalValue() {
        return BigDecimal.valueOf(CONTRACT_SIZE).multiply(requireExchangeRate());
    }

    /**
     * Derives maintenance margin as {@code contractSize * exchangeRate * 10%}.
     *
     * @return derived maintenance margin
     */
    public BigDecimal calculateMaintenanceMargin() {
        return calculateNominalValue().multiply(MAINTENANCE_MARGIN_RATE);
    }

    private BigDecimal requireExchangeRate() {
        return Objects.requireNonNull(exchangeRate, "exchangeRate must not be null");
    }
}
