package com.banka1.stock_service.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * JPA entity representing a current market listing snapshot stored in the {@code listing} table.
 *
 * <p>The persistent state stores the latest market data shown for one tradable security on one exchange.
 * The model intentionally keeps {@code securityId} as a generic identifier because the listing can point
 * to different security tables depending on {@code listingType}.
 *
 * <p>The listing uses:
 *
 * <ul>
 *     <li>{@code securityId} to identify the underlying domain security</li>
 *     <li>{@code listingType} to describe whether that security is a stock, futures contract, or FX pair</li>
 *     <li>{@code stockExchangeId} to point to the exchange where the security is quoted</li>
 * </ul>
 */
@Entity
@Table(name = "listing")
@Getter
@Setter
public class Listing {

    /**
     * Multiplier used to derive initial margin cost from a maintenance margin value.
     */
    private static final BigDecimal INITIAL_MARGIN_MULTIPLIER = new BigDecimal("1.10");

    /**
     * Technical primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Identifier of the underlying security entity.
     */
    @Column(name = "security_id", nullable = false)
    private Long securityId;

    /**
     * Security category used to interpret {@code securityId}.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "listing_type", nullable = false, length = 16)
    private ListingType listingType;

    /**
     * Exchange where the listing is quoted.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "stock_exchange_id", nullable = false)
    private StockExchange stockExchange;

    /**
     * Exchange-specific ticker shown to users.
     */
    @Column(name = "ticker", nullable = false, length = 64)
    private String ticker;

    /**
     * Human-readable security name shown in listing screens.
     */
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    /**
     * Timestamp when the market snapshot was last refreshed.
     */
    @Column(name = "last_refresh", nullable = false)
    private LocalDateTime lastRefresh;

    /**
     * Last traded price in the latest snapshot.
     */
    @Column(name = "price", nullable = false, precision = 19, scale = 8)
    private BigDecimal price;

    /**
     * Current ask price in the latest snapshot.
     */
    @Column(name = "ask", nullable = false, precision = 19, scale = 8)
    private BigDecimal ask;

    /**
     * Current bid price in the latest snapshot.
     */
    @Column(name = "bid", nullable = false, precision = 19, scale = 8)
    private BigDecimal bid;

    /**
     * Absolute price change reported in the latest snapshot.
     */
    @Column(name = "change", nullable = false, precision = 19, scale = 8)
    private BigDecimal change;

    /**
     * Latest traded volume in the current snapshot.
     */
    @Column(name = "volume", nullable = false)
    private Long volume;

    /**
     * Derives dollar volume as {@code volume * price}.
     *
     * @return derived dollar volume
     */
    public BigDecimal calculateDollarVolume() {
        return BigDecimal.valueOf(requireVolume()).multiply(requirePrice());
    }

    /**
     * Derives initial margin cost as {@code maintenanceMargin * 1.1}.
     *
     * @param maintenanceMargin already-derived maintenance margin
     * @return derived initial margin cost
     */
    public BigDecimal calculateInitialMarginCost(BigDecimal maintenanceMargin) {
        return requireMaintenanceMargin(maintenanceMargin).multiply(INITIAL_MARGIN_MULTIPLIER);
    }

    private BigDecimal requirePrice() {
        return Objects.requireNonNull(price, "price must not be null");
    }

    private long requireVolume() {
        return Objects.requireNonNull(volume, "volume must not be null");
    }

    private BigDecimal requireMaintenanceMargin(BigDecimal maintenanceMargin) {
        return Objects.requireNonNull(maintenanceMargin, "maintenanceMargin must not be null");
    }
}
