package com.banka1.stock_service.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;

/**
 * JPA entity representing a stock option stored in the {@code stock_option} table.
 *
 * <p>The persistent state stores the static option-contract metadata, while maintenance
 * margin remains a derived value because it depends on the current price of the
 * underlying stock.
 *
 * <p>The option uses:
 *
 * <ul>
 *     <li>{@code ticker} as the stable business identifier</li>
 *     <li>{@code stock_listing_id} to point to the underlying {@link Stock}</li>
 *     <li>{@code optionType}, {@code strikePrice}, and {@code settlementDate}
 *     to describe the contract terms</li>
 * </ul>
 *
 * <p>Options are not modeled as a standalone listing catalog in the current API surface.
 * Instead, they belong to one underlying stock and are intended to be presented alongside it.
 */
@Entity
@Table(name = "stock_option")
@Getter
@Setter
public class StockOption {

    /**
     * Standard contract size used for equity options in this domain model.
     */
    public static final int CONTRACT_SIZE = 100;

    /**
     * Multiplier used to derive maintenance margin from the current underlying stock price.
     */
    private static final BigDecimal MAINTENANCE_MARGIN_RATE = new BigDecimal("0.50");

    /**
     * Technical primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique option ticker used as the stable business key.
     */
    @Column(name = "ticker", nullable = false, length = 64, unique = true)
    private String ticker;

    /**
     * Underlying stock referenced by the {@code stock_listing_id} foreign key.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "stock_listing_id", nullable = false)
    private Stock stock;

    /**
     * Type of option contract, either {@link OptionType#CALL} or {@link OptionType#PUT}.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "option_type", nullable = false, length = 16)
    private OptionType optionType;

    /**
     * Strike price agreed by the option contract.
     */
    @Column(name = "strike_price", nullable = false, precision = 19, scale = 4)
    private BigDecimal strikePrice;

    /**
     * Implied volatility stored as a decimal value.
     */
    @Column(name = "implied_volatility", nullable = false, precision = 19, scale = 8)
    private BigDecimal impliedVolatility;

    /**
     * Number of currently open contracts for this option.
     */
    @Column(name = "open_interest", nullable = false)
    private Integer openInterest;

    /**
     * Last traded option price used by stock-details consumers.
     */
    @Column(name = "last_price", nullable = false, precision = 19, scale = 8)
    private BigDecimal lastPrice;

    /**
     * Current ask price for the option contract.
     */
    @Column(name = "ask", nullable = false, precision = 19, scale = 8)
    private BigDecimal ask;

    /**
     * Current bid price for the option contract.
     */
    @Column(name = "bid", nullable = false, precision = 19, scale = 8)
    private BigDecimal bid;

    /**
     * Current traded option volume.
     */
    @Column(name = "volume", nullable = false)
    private Long volume;

    /**
     * Settlement or expiration date of the option contract.
     */
    @Column(name = "settlement_date", nullable = false)
    private LocalDate settlementDate;

    /**
     * Returns the fixed contract size for this option.
     *
     * @return contract size, always {@value #CONTRACT_SIZE}
     */
    public int getContractSize() {
        return CONTRACT_SIZE;
    }

    /**
     * Derives maintenance margin as {@code contractSize * 50% * stockPrice}.
     *
     * <p>Example:
     * if {@code contractSize = 100} and {@code stockPrice = 212.40},
     * the derived maintenance margin is {@code 10620.0000}.
     *
     * @param stockPrice current price of the underlying stock
     * @return derived maintenance margin
     */
    public BigDecimal calculateMaintenanceMargin(BigDecimal stockPrice) {
        return BigDecimal.valueOf(CONTRACT_SIZE)
                .multiply(requireStockPrice(stockPrice))
                .multiply(MAINTENANCE_MARGIN_RATE);
    }

    /**
     * Determines whether the option is currently in the money for the provided stock price.
     *
     * <p>Calls are in the money when the stock price is above the strike price. Puts are in the
     * money when the stock price is below the strike price. At-the-money contracts are treated as
     * out of the money for this simplified API response.
     *
     * @param stockPrice current price of the underlying stock
     * @return {@code true} when the option is in the money
     */
    public boolean isInTheMoney(BigDecimal stockPrice) {
        BigDecimal currentStockPrice = requireStockPrice(stockPrice);
        BigDecimal currentStrikePrice = requireStrikePrice();

        return switch (requireOptionType()) {
            case CALL -> currentStockPrice.compareTo(currentStrikePrice) > 0;
            case PUT -> currentStockPrice.compareTo(currentStrikePrice) < 0;
        };
    }

    private BigDecimal requireStockPrice(BigDecimal stockPrice) {
        return Objects.requireNonNull(stockPrice, "stockPrice must not be null");
    }

    private BigDecimal requireStrikePrice() {
        return Objects.requireNonNull(strikePrice, "strikePrice must not be null");
    }

    private OptionType requireOptionType() {
        return Objects.requireNonNull(optionType, "optionType must not be null");
    }
}
