package com.banka1.card_service.domain;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.Version;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Shared JPA base entity with persistence metadata used by all database entities in this service.
 * The purpose of this class is to keep infrastructure fields in one place instead of duplicating them
 * in every entity. Business data such as card number, status, CVV hash, or expiration date belongs
 * to concrete entities such as {@link Card}.
 */
@MappedSuperclass
@Getter
@Setter
@NoArgsConstructor
public abstract class BaseEntity {

    /**
     * Surrogate database primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Optimistic-lock field maintained by JPA.
     * This protects against lost updates when the same row is modified concurrently.
     */
    @Version
    private Long version;

    /**
     * Soft-delete marker reserved for logical deletion scenarios.
     * The current card flow does not toggle it yet, but the field is part of the shared persistence model.
     */
    @Column(name = "deleted", nullable = false)
    private boolean deleted = false;

    /**
     * Timestamp automatically assigned on the initial insert.
     */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp automatically refreshed whenever the entity is updated.
     */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
